# Generated by Django 3.2.7 on 2022-01-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adminName', models.CharField(max_length=100)),
                ('adminLastName', models.CharField(max_length=100)),
                ('adminEmail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('admin_otp', models.IntegerField(default=567)),
                ('adminPhone', models.CharField(max_length=11, null=True)),
                ('adminProfile_pic', models.FileField(blank=True, default='admin_profile/1.png', null=True, upload_to='admin_profile/')),
                ('gender', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('home_country', models.CharField(max_length=10, null=True)),
                ('home_state', models.CharField(max_length=50, null=True)),
                ('home_city', models.CharField(max_length=50, null=True)),
                ('home_pincode', models.IntegerField(blank=True, null=True)),
                ('home_address', models.CharField(max_length=100, null=True)),
                ('view', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
                ('qty', models.IntegerField(null=True)),
                ('desc', models.CharField(max_length=300, null=True)),
                ('product_pic', models.FileField(blank=True, default='pizzriea.JPG', null=True, upload_to='product/images')),
                ('views_count', models.IntegerField(default=0)),
                ('view', models.BooleanField(default=False)),
                ('adminUser_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.adminuser')),
                ('c_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='shop_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200)),
                ('shop_type', models.CharField(max_length=200)),
                ('shop_country', models.CharField(max_length=30)),
                ('shop_state', models.CharField(max_length=50)),
                ('shop_city', models.CharField(max_length=50)),
                ('shop_pincode', models.IntegerField(blank=True, null=True)),
                ('shop_address', models.CharField(max_length=100)),
                ('view', models.BooleanField(default=False)),
                ('owner_id_proof', models.FileField(upload_to='images/')),
                ('elc_bill', models.FileField(upload_to='images/')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.adminuser')),
            ],
        ),
        migrations.CreateModel(
            name='retailer_FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('overall_experience', models.CharField(max_length=20)),
                ('timely_response', models.CharField(max_length=30)),
                ('our_support', models.CharField(max_length=30)),
                ('overall_setisfaction', models.CharField(max_length=30)),
                ('suggestion', models.CharField(blank=True, max_length=1000)),
                ('view', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.adminuser')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.FileField(blank=True, default='pizzriea.JPG', null=True, upload_to='product/images')),
                ('adminUser_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.adminuser')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shop_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.shop_detail'),
        ),
    ]
